---
# tasks file for debian-es
- name: Installing FTP server on Debian
  apt:
          name: vsftpd
          state: latest
          update_cache: yes

- name: Starting the FTP service
  service:
          name: vsftpd
          state: started
          enabled: yes

- name: Creating an FTP user
  user:
          name: '{{ user }}'
          password: '{{ ftp_pass }}'

- name: Denying User to Access SSH
  lineinfile:
          path: /etc/ssh/sshd_config
          line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: Restarting SSHd Service
  service:
          name: sshd
          state: restarted
  when: successfully_denied.changed

- name: Limiting FTP users to their own home directory
  replace:
          path: /etc/vsftpd.conf
          regexp: '#chroot_local_user=YES'
          replace: 'chroot_local_user=YES'

- name: Configuring FTP file
  lineinfile:
          path: /etc/vsftpd.conf
          line: '{{ ftp_debian }}'

- name: Restarting vsftpd
  service:
          name: vsftpd
          state: restarted
